<a href="https://colab.research.google.com/github/mejoryoonginista/EAS1/blob/main/Copia_de_R_Python_Vectors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src="https://i.imgur.com/6U6q5jQ.png"/>

<a target="_blank" href="https://colab.research.google.com/github/PythonVersusR/basicDataStructures_vectors/blob/main/R_Python_Vectors.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Vectors in R and Python

In [1]:
## if needed, run this and RESTART KERNEL
# import os
# os.environ['R_HOME'] ='/Library/Frameworks/R.framework/Resources'

In [2]:
%load_ext rpy2.ipython

## 1. Creating

In [3]:
import numpy as np

namesP=np.array(["Juggy", "Karla", "Taehyun", "Yoongi","Jordan"])
agesP=np.array([27,21,21,30,34])
countryP=np.array(["Mexico", "Peru", "Canada", "Korea","United States"])
occupationP=np.array(["Teacher", "Publicist", "Call center agent", "Doctor","Psychologist"])

In [4]:
namesP

array(['Juggy', 'Karla', 'Taehyun', 'Yoongi', 'Jordan'], dtype='<U7')

In [5]:
%%R
namesR=c("Juggy", "Karla", "Taehyun", "Yoongi","Jordan")
agesR=c(27,21,21,30,34)
countryR=c("Mexico", "Peru", "Canada", "Korea","United States")
occupationR=c("Teacher", "Publicist", "Call center agent", "Doctor","Psychologist")

In [6]:
%%R
namesR

[1] "Juggy"   "Karla"   "Taehyun" "Yoongi"  "Jordan" 


## 2. Accessing

In [7]:
agesP[3]

30

In [8]:
%%R
agesR[1]

[1] 27


In [9]:
countryP[-1]

'United States'

In [10]:
%%R
tail(countryR,2)

[1] "Korea"         "United States"


### Slices

In [11]:
agesP[1:2] #second to third

array([21])

In [12]:
%%R
agesR[2:4]

[1] 21 21 30


In [13]:
agesP[[0,2,3]]

array([27, 21, 30])

In [14]:
%%R
agesR[c(1,3,4)]

[1] 27 21 30


## Replacing

### by Position

In [15]:
countryP[0]="Norway"

# list changed:
countryP

array(['Norway', 'Peru', 'Canada', 'Korea', 'United States'], dtype='<U13')

In [16]:
%%R
countryR[4]="Uruguay"

# list changed:
countryR

[1] "Mexico"        "Peru"          "Canada"        "Uruguay"      
[5] "United States"


### By Value

In [17]:
countryP=np.char.replace(countryP, 'Peru', 'China')
countryP

array(['Norway', 'China', 'Canada', 'Korea', 'United States'],
      dtype='<U13')

In [18]:
%%R
countryR[countryR=='Canada']="Italy"
countryR

[1] "Mexico"        "Peru"          "Italy"         "Uruguay"      
[5] "United States"


## Deleting

### By Position

In [19]:
countryP=np.delete(countryP,-1) #the last one
countryP

array(['Norway', 'China', 'Canada', 'Korea'], dtype='<U13')

In [20]:
%%R
countryR=countryR[-length(countryR)] #the last one
countryR

[1] "Mexico"  "Peru"    "Italy"   "Uruguay"


In [21]:
# for several positions

vectorP=np.array([1,2,3,4,5,6])
vectorP=np.delete(vectorP,range(1,3)) #delete row 1 and 3
#now:
vectorP

array([1, 4, 5, 6])

In [22]:
%%R

vectorR=c(1,2,3,4,5,6)
vectorR=vectorR[-c(2:5)] #delete row 2 and 5

#now:
vectorR

[1] 1 6


In [23]:
# non consecutive
byeIndex=[1, 3, 5]

vectorP=np.array([11,22,33,44,55,66])
new_vectorP=np.delete(vectorP,byeIndex)

#now:
new_vectorP

array([11, 33, 55])

In [24]:
%%R
vectorR=c(11,22,33,44,55,66)
new_vectorR=vectorR[-c(1,3,5)]
new_vectorR

[1] 22 44 66


### by Value

In [25]:
vectorP=np.array([1,5,45,5,4])

vectorP=np.delete(vectorP, np.where(vectorP == 5))

#  changed:
vectorP

array([ 1, 45,  4])

In [26]:
%%R

vectorR=c(1,39,45,6,39)
vectorR=vectorR[vectorR!=39]
vectorR


[1]  1 45  6


In [27]:
# by value
vectorP=np.array([1,7,20,7,7])

#vectorP=
vectorP=np.delete(vectorP, np.isin(vectorP,[1,20]))

#  changed:
vectorP

array([7, 7, 7])

In [28]:
%%R

vectorR=c(1,35,35,8,8)
vectorR=vectorR[!vectorR%in%c(1,35)]
vectorR

[1] 8 8


## Inserting values

### at the End

In [29]:
vectorP=np.array([1,2,3,4])
vectorP=np.append(vectorP,93)
vectorP

array([ 1,  2,  3,  4, 93])

In [30]:
%%R
vectorR=c(1,2,3,4)
vectorR=c(vectorR,9)
vectorR

[1] 1 2 3 4 9


### in a particular location

In [31]:
vectorP=np.array([1,2,3,4])
vectorP=np.insert(vectorP,obj=2,values=11) #obj is position 3
vectorP

array([ 1,  2, 11,  3,  4])

In [32]:
%%R
vectorR=c(1,2,3,4)
vectorR=append(vectorR,44,after=3)
vectorR

[1]  1  2  3 44  4


## Concatenating

In [33]:
import numpy as np

vectorP1=np.array([1,2,3,4])
vectorP2=np.array(['b','z'])
vectorP12=np.concatenate((vectorP1,vectorP2))
vectorP12

array(['1', '2', '3', '4', 'b', 'z'], dtype='<U21')

In [34]:
%%R
vectorR1=c(1,2,3,4)
vectorR2=c('m','y')
vectorR12=c(vectorR1,vectorR2)
vectorR12

[1] "1" "2" "3" "4" "m" "y"


Remember that vectors support just one data type, and coercion will activate when different data types are detected.

In [35]:
vectorP1=np.array([1,2,3,4,"0"])
vectorP1

array(['1', '2', '3', '4', '0'], dtype='<U21')

In [36]:
%%R
vectorR1=c(1,2,3,4,"0")
vectorR1

[1] "1" "2" "3" "4" "0"
